import Test from '@/components/Test';
import { PrimaryC } from '@/stories/Btn/Btn.stories';
import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Storybook</title>
        <meta name="description" content="Generated by Hefnii" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Storybook</h1>
      </main>

      <section>
        Components
        <Test />
        <PrimaryC
          variant="danger"
          onClick={() => {
            console.log('Thats it');
          }}>
          Button Component
        </PrimaryC>
      </section>

      <footer className={styles.footer}>Hefnii</footer>
    </div>
  );
}
