import React from "react";
import Head from "next/head";
import { PrimaryBtn, PrimaryC } from "../stories/Btn/Btn.stories";
import styles from "../styles/Home.module.css";
import Center from "../stories/Center/Center";
import Btn from "../stories/Btn/Btn";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Storybook</title>
        <meta name="description" content="Generated by Hefnii" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Storybook</h1>
      </main>

      <section>
        Components
        <PrimaryC
          variant="danger"
          onClick={() => {
            console.log("Thats it");
          }}
        >
          Button Component
        </PrimaryC>
      </section>

      <footer className={styles.footer}>Hefnii</footer>
    </div>
  );
}
